version: 1.0.{build}
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
install:
  # to install downloader do: "cinst wget -x86"
  # the format is: "wget -q URL -O c:\path-to-file\file_name"
  # special format is: "wget -q --no-check-certificate URL -O c:\path-to-file\file_name"
  # that accounts for downloading from e.g. https://googledrive.com/host/$HASH
  # -
  # to install unzipper do: "cinst 7zip.commandline -x86"
  # the format is: "7z x c:\path-to-archive\archive.zip -oc:\path-where-unzip -y > nul"
  - cmd: cinst wget -x86
  - cmd: cinst 7zip.commandline -x86
  - cmd: wget http://mirrors.advancedhosters.com/apache/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip
  - cmd: 7z x apache-maven-3.2.5-bin.zip -y > nul
  #- cmd: cinst maven
  - cmd: echo %cd%
  - cmd: dir
  - cmd: dir C:\projects\cola-tests\apache-maven-3.2.5
  - cmd: set M2_HOME=C:\projects\cola-tests\apache-maven-3.2.5
  #- cmd: set MAVEN_OPTS="-Xms256m -Xmx512m"
  - cmd: set PATH=%M2_HOME%\bin;%PATH%
before_build:
  - java -version
  - mvn -version
build_script:
  - mvn clean install
